return {
    firacode = {
        family = 'FiraCode Nerd Font',
        weight = 'Medium',
        size = 12,
        harfbuzz = {
            'cv02',
            'cv05',
            'cv09',
            'cv14',
            'cv16',
            'cv25',
            'cv26',
            'cv27',
            'cv31',
            'cv32',
            'zero',
            'ss04',
            'ss05',
            'ss03',
            'ss07',
            'ss09',
        },
    },
    monaspace = {
        family = 'Monaspace Neon',
        weight = 'Medium',
        size = 12,
        harfbuzz = {
            'ss01',
            'ss02',
            'ss03',
            'ss06',
            'ss07',
            'ss08',
            'cv61',
        },
    },
}
