# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$hostname\
$directory\
$python\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$container
$character"""

command_timeout = 5000

# Catppuccin all the things!
palette = "catppuccin_mocha"

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[>](bold sky)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[>](bold red)" # The "success_symbol" segment is being set to "➜" with the color "bold green"


[hostname]
format = "[$ssh_symbol]($style) "

[python]
#format = "[${symbol} ${virtualenv}]($style)"
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
detect_extensions = []
detect_files = []

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_metrics]
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
