- name: Download monaspace Nerd Font
  ansible.builtin.get_url:
    dest: /tmp
    url: https://github.com/githubnext/monaspace/releases/download/v1.400/monaspace-webfont-nerdfonts-v1.400.zip
    mode: '0644'

- name: Ensure fonts directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.local/share/fonts"
    state: directory
    recurse: true

- name: Install FiraCode Nerd Font
  ansible.builtin.unarchive:
    src: /tmp/monaspace-webfont-nerdfonts-v1.400.zip
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/share/fonts"
    remote_src: true
