#!/usr/bin/bash

set -e

changed_files="$(git diff --cached --name-only)"

# Rust checks
if echo "$changed_files" | grep -q -e "^fact" -e "^third_party" -e "^tests"; then
	if [[ ! -e .venv ]]; then
		uv venv .venv
		uv pip install -r tests/requirements.txt
	fi

	# shellcheck disable=SC1091
	source .venv/bin/activate
	make format-check lint
	deactivate
fi

# eBPF checks
if echo "$changed_files" | grep -q -e "^fact-ebpf" -e "^fact/src/bpf"; then
	if [[ -t 0 ]]; then
		cargo stest --features=bpf-test --all
	else
		echo "Skipping eBPF tests"
	fi
fi

# Image build
if echo "$changed_files" | grep -q -e "^Containerfile$"; then
	# Test the image build
	make image
fi

# GHA checks
if git diff --cached --name-only | grep -q "^\.github/workflows"; then
	echo "Running actionlint..."
	actionlint
fi
