- name: Download Catppuccin cursors
  ansible.builtin.get_url:
    dest: /tmp
    url: https://github.com/catppuccin/cursors/releases/latest/download/catppuccin-mocha-dark-cursors.zip
    mode: '0644'

- name: Create icons directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.icons"
    state: directory
    mode: '0755'

- name: Install Catppuccin cursor
  ansible.builtin.unarchive:
    src: /tmp/catppuccin-mocha-dark-cursors.zip
    dest: "{{ ansible_env.HOME }}/.icons"

- name: Make catppuccin the default cursor
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.icons/catppuccin-mocha-dark-cursors"
    dest: "{{ ansible_env.HOME }}/.icons/default"
    state: link
