- name: Install utilities
  become: true
  ansible.builtin.dnf:
    name:
      - ansible-collection-community-general
      - bat
      - clang
      - cmake
      - container-selinux
      - cowsay
      - fd-find
      - fzf
      - glibc-devel.i686
      - golang
      - htop
      - jq
      - kernel-devel
      - llvm
      - make
      - neovim
      - nodejs
      - perl
      - podman
      - podman-compose
      - podman-docker
      - protobuf-devel
      - ripgrep
      - rustup
      - tmux
      - uv
      - wget
      - zsh
    state: latest

- name: Update system
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  tags:
    - update

- name: install rust
  ansible.builtin.command: rustup-init -y

- name: Silence podman warning on docker emulation
  become: true
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    mode: '0644'

- name: Use zsh as default shell
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: Change npm install prefix
  ansible.builtin.command: npm config set prefix {{ ansible_env.HOME }}/.local
