- name: Install utilities
  become: true
  ansible.builtin.dnf:
    name:
      - ansible-collection-community-general
      - bat
      - btop
      - clang
      - cmake
      - container-selinux
      - cowsay
      - fd-find
      - fzf
      - git-delta
      - glibc-devel.i686
      - golang
      - jq
      - kernel-devel
      - make
      - neovim
      - nodejs
      - perl
      - protobuf-devel
      - ripgrep
      - rustup
      - socat
      - tmux
      - uv
      - wget
      - zsh
    state: latest

- name: Update system
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  tags:
    - update

- name: install rust
  ansible.builtin.command: rustup-init -y

- name: Change npm install prefix
  ansible.builtin.command: npm config set prefix {{ ansible_facts['env']['HOME'] }}/.local


- name: Install zsh-patina
  ansible.builtin.shell: |
    . $HOME/.cargo/env
    cargo install --locked zsh-patina
