#!/usr/bin/env bash

set -euo pipefail

kubectl rollout status deploy/bpfd-builder > /dev/null
kubectl exec deploy/bpfd-builder -- cargo +nightly fmt --check
kubectl exec deploy/bpfd-builder -- cargo +nightly clippy
