FROM fedora:44

RUN dnf install -y \
    gcc \
    gcc-c++ \
    make \
    cmake \
    git \
    curl \
    ca-certificates \
    openssl \
    openssl-devel \
    pkg-config \
    wget \
    tar \
    gzip \
    zsh \
    nodejs \
    npm \
    python3 \
    python3-pip \
    golang \
    ripgrep \
    fd-find \
    rust \
    cargo \
    clippy \
    rust-analyzer \
    rustfmt \
    libnotify \
    tmux \
    && npm install -g @anthropic-ai/claude-code \
    && dnf clean all \
    && rm -rf /var/cache/dnf

ENV GOPATH="/go"
ENV PATH="${GOPATH}/bin:${PATH}"

ENTRYPOINT ["claude"]
