---
- name: Install my dotfiles on remote user
  hosts: all

  tasks:
    - name: Ensure .config directory exists
      file:
        path: "{{ ansible_env.HOME + '/.config' }}"
        state: directory

    - name: Install zsh configuration files
      shell: "{{ ansible_env.HOME + '/go/src/github.com/molter73/dotfiles/zsh/install.sh' }}"

    - name: Install starship.rs
      shell: cargo install starship

    - name: Link starship configuration
      file:
        src: "{{ ansible_env.HOME + '/go/src/github.com/molter73/dotfiles/starship.toml' }}"
        dest: "{{ ansible_env.HOME + '/.config/starship.toml' }}"
        state: link
