---
- name: Install my dotfiles on remote user
  hosts: all
  vars:
    dotfiles_repo: "{{ ansible_env.HOME + '/go/src/github.com/molter73/dotfiles' }}"
    dotfiles_xdg_config: "{{ ansible_env.HOME + '/.config' }}"
  roles:
    - dotfiles
