---
- name: Install latest version of all used lsps
  hosts: all

  tasks:
    - name: Install LSPs from DNF
      become: true
      ansible.builtin.dnf:
        name:
        - clang-tools-extra
        - golang-x-tools-gopls
        - python3-flake8
        - python3-autopep8
        - python3-ansible-lint
        - hadolint
        - shfmt
        - shellcheck
        state: latest
      tags:
      - dnf

    - name: Install LSPs from brew
      community.general.homebrew:
        name:
        - lua-language-server
        - texlab
        state: latest
        upgrade_all: true
      tags:
      - brew

    - name: Install LSPs from pip
      ansible.builtin.pip:
        name:
        - cmake-language-server
        - basedpyright
        state: latest
      tags:
      - pip

    - name: Install yamlls
      community.general.npm:
        name: yaml-language-server
        global: true
        state: latest
      tags:
      - npm

    - name: Install bashls
      community.general.npm:
        name: bash-language-server
        global: true
        state: latest
      tags:
      - npm

    - name: Install ansiblels
      community.general.npm:
        name: '@ansible/ansible-language-server'
        global: true
        state: latest
      tags:
      - npm

    - name: Install vscode language servers
      community.general.npm:
        name: vscode-langservers-extracted
        global: true
        state: latest
      tags:
      - npm

    - name: Install actionlint
      ansible.builtin.command:
        cmd: go install github.com/rhysd/actionlint/cmd/actionlint@latest
        creates: "{{ lookup('env', 'GOPATH') }}/bin/actionlint"
      tags:
      - go
