---
- name: Setup rootfull podman
  hosts: all
  tasks:
    - name: Ensure podman service is up and running
      become: true
      ansible.builtin.systemd_service:
        name: podman
        enabled: true
        state: started

    - name: Add podman group
      become: true
      ansible.builtin.group:
        name: podman
        state: present

    - name: Add user to podman group
      become: true
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: podman
        append: true

    - name: Chown the podman run directory
      become: true
      ansible.builtin.file:
        group: podman
        owner: root
        mode: '0770'
        path: /run/podman

    - name: Chown the podman socket
      become: true
      ansible.builtin.file:
        group: podman
        owner: root
        mode: '0660'
        path: /run/podman/podman.sock

    - name: Persist permission changes
      become: true
      ansible.builtin.copy:
        content: D! /run/podman 0770 root podman
        dest: /etc/tmpfiles.d/podman.conf
        mode: '644'

    - name: Create podman context
      ansible.builtin.command: |
        podman system connection add -d dev unix:///run/podman/podman.sock

    - name: Enable podman API
      become: true
      ansible.builtin.systemd_service:
        name: podman.socket
        enabled: true
        state: started

    - name: Disable podman relabeling of mounts
      become: true
      ansible.builtin.lineinfile:
        path: /usr/share/containers/containers.conf
        regexp: '^# label ='
        line: label = false
