---
- name: Syncing of files from remote
  hosts: all

  tasks:
    - name: Sync personal repos
      ansible.posix.synchronize:
        src: "{{ ansible_env.HOME + '/go/src/github.com/molter73' }}"
        dest: "{{ lookup('env', 'HOME') + '/go/src/github.com/' }}"
        mode: pull
      tags:
      - personal

    - name: Sync StackRox repos
      ansible.posix.synchronize:
        src: "{{ ansible_env.HOME + '/go/src/github.com/stackrox' }}"
        dest: "{{ lookup('env', 'HOME') + '/go/src/github.com/' }}"
        mode: pull
      tags:
      - stackrox

    - name: Sync bpfd repos
      ansible.posix.synchronize:
        src: "{{ ansible_env.HOME + '/go/src/github.com/bpfd-dev' }}"
        dest: "{{ lookup('env', 'HOME') + '/go/src/github.com/' }}"
        mode: pull
      tags:
      - bpfd

    - name: Sync Falco repos
      ansible.posix.synchronize:
        src: "{{ ansible_env.HOME + '/go/src/github.com/falcosecurity' }}"
        dest: "{{ lookup('env', 'HOME') + '/go/src/github.com/' }}"
        mode: pull
      tags:
      - falco

    - name: Upload libbpf repos
      ansible.posix.synchronize:
        src: "{{ ansible_env.HOME + '/go/src/github.com/libbpf' }}"
        dest: "{{ lookup('env', 'HOME') + '/go/src/github.com/' }}"
        mode: pull
      tags:
      - bpfd
