---
- name: Syncing of files to remote
  hosts: all

  tasks:
    - name: Create github.com directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME + '/go/src/github.com' }}"
        state: directory
        mode: '0755'

    - name: Sync personal repos
      ansible.posix.synchronize:
        dest: "{{ ansible_env.HOME + '/go/src/github.com/' }}"
        src: "{{ lookup('env', 'HOME') + '/go/src/github.com/molter73' }}"
        delete: true
        rsync_opts:
          - '--exclude=target/'
      tags:
        - personal

    - name: Sync StackRox repos
      ansible.posix.synchronize:
        dest: "{{ ansible_env.HOME + '/go/src/github.com/' }}"
        src: "{{ lookup('env', 'HOME') + '/go/src/github.com/stackrox' }}"
        delete: true
        rsync_opts:
          - '--exclude=cmake-build/'
          - '--exclude=build/'
          - '--exclude=THIRD_PARTY_NOTICES/'
          - '--exclude=container-logs/'
          - '--exclude=collector/container/bin/'
      tags:
        - stackrox

    - name: Sync bpfd repos
      ansible.posix.synchronize:
        dest: "{{ ansible_env.HOME + '/go/src/github.com/' }}"
        src: "{{ lookup('env', 'HOME') + '/go/src/github.com/bpfd-dev' }}"
        delete: true
        rsync_opts:
          - '--exclude=target/'
      tags:
        - bpfd

    - name: Sync Falco repos
      ansible.posix.synchronize:
        dest: "{{ ansible_env.HOME + '/go/src/github.com/' }}"
        src: "{{ lookup('env', 'HOME') + '/go/src/github.com/falcosecurity' }}"
        delete: true
        rsync_opts:
          - '--exclude=build/'
      tags:
        - falco

    - name: Upload libbpf repos
      ansible.posix.synchronize:
        dest: "{{ ansible_env.HOME + '/go/src/github.com/' }}"
        src: "{{ lookup('env', 'HOME') + '/go/src/github.com/libbpf' }}"
        delete: true
      tags:
        - bpfd
