---
- name: Basic provisioning
  hosts: all

  tasks:
    - name: Setup kubernetes repo
      become: true
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Install utilities
      become: true
      dnf:
        name:
          - cmake
          - fzf
          - golang
          - jq
          - kernel-devel
          - kubectl
          - clang
          - llvm
          - make
          - neovim
          - nfs-utils
          - perl
          - podman
          - podman-docker
          - container-selinux
          - wget
          - yarnpkg
          - zsh
          - fd-find
          - ripgrep
        state: latest

    - name: Update system
      become: true
      dnf:
        name: "*"
        state: latest
        update_cache: true
      tags:
      - update

    - name: Silence podman warning on docker emulation
      become: true
      file:
        path: /etc/containers/nodocker
        state: touch
        mode: u=rw,g=r,o=r

    - name: Enable podman API
      become: true
      systemd:
        name: podman.socket
        enabled: true
        state: started

    - name: Disable podman relabeling of mounts
      become: true
      lineinfile:
        path: /usr/share/containers/containers.conf
        regexp: '^# label ='
        line: label = false

    - name: Use zsh as default shell
      become: true
      user:
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/zsh

    - name: Get rustup install script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh
        mode: '0755'

    - name: Install rustup
      shell: /tmp/rustup.sh -y

    - name: Remove install script
      file:
        path: /tmp/rustup.sh
        state: absent
