---
- name: Provision workstation
  hosts: all

  roles:
    - utilities
    - starship
    - podman
    - opencode
    - nono
    - kubectl
    - sway
    - catppuccin
    - firacode
    - monaspace
    - dotfiles
    - lsp
    - rootfull-podman
