#!/usr/bin/env zsh

# XDG config
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_BIN_HOME="${HOME}/.local/bin"

export ZSH="${XDG_CONFIG_HOME}/zsh"

export EDITOR='nvim'
export VISUAL="$EDITOR"

# Use buildkit with docker
export DOCKER_BUILDKIT=1

# go variables
export GOPATH="${HOME}/go"
#   Restore default on Fedora 42 and older
#   https://developer.fedoraproject.org/tech/languages/go/go-installation.html
export GOPROXY="https://proxy.golang.org,direct"
export GOSUMDB="sum.golang.org"
export GOTOOLCHAIN="auto"

# k3s cluster
export KUBECONFIG="${XDG_CONFIG_HOME}/kube.yml"
export KUBE_EDITOR="nvim"

# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"${HOME}/.cargo/bin":*) ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$HOME/.cargo/bin:$PATH"
        ;;
esac

# Path adjustments
#   Stackrox workflow scripts
export PATH="$PATH:${HOME}/go/src/github.com/stackrox/workflow/bin"
#   Go binaries
export PATH=$PATH:$GOPATH/bin
#   CodeReady containers
export PATH="$PATH:${HOME}/.crc/bin/oc"
#   My binaries before anything else
export PATH="${XDG_BIN_HOME}:$PATH"

if command -v yarn > /dev/null; then
    export PATH="$PATH:$(yarn global bin)"
fi

# For devcontainers
if [[ -d /opt/nvim-linux-x86_64/bin ]]; then
    export PATH="$PATH:/opt/nvim-linux-x86_64/bin"
fi

# Set catppuccin for fzf colors
export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--color=selected-bg:#45475a \
--color=border:#313244,label:#cdd6f4"

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

# Gemini
if [[ -f ~/.gemini-key ]]; then
    source ~/.gemini-key
fi

# Variables for dedicated hosts
if [[ -f "$ZSH/localenv" ]]; then
    source "$ZSH/localenv"
fi
