#!/usr/bin/env zsh

export ZSH="${HOME}/.config/zsh"

export EDITOR='nvim'
export VISUAL="$EDITOR"

# Use buildkit with docker
export DOCKER_BUILDKIT=1

# go variables
export GOPATH=$HOME/go

# Java Home
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home"

# k3s cluster
export KUBECONFIG="${HOME}/.kube/k3s.yaml"
export KUBE_EDITOR="nvim"

# OSCI stuff
export CONTAINER_ENGINE=podman
