#!/usr/bin/env zsh

export ZSH="${HOME}/.config/zsh"

export EDITOR='nvim'
export VISUAL="$EDITOR"

# Enable zsh auto-completion
autoload -Uz compinit
compinit

# Enable bash completion compatibility
autoload bashcompinit
bashcompinit

# Highlight selection with tab completion
zstyle ':completion:*' menu select
zstyle ':completion:*' special-dirs true

# Share history
setopt share_history

# alias
alias beggar="VAGRANT_CWD=${HOME}/vagrant/ vagrant"
alias k=kubectl
alias krox="kubectl -n stackrox"
alias dcu='docker context use'
alias ssh-kitten='kitty +kitten ssh'
alias ls='ls --color=auto'

# stackrox stuff
if [[ -f "${HOME}/.infra" ]]; then
    source "${HOME}/.infra"
fi

if [[ -f "${HOME}/go/src/github.com/stackrox/workflow/env.sh" ]]; then
    source "${HOME}/go/src/github.com/stackrox/workflow/env.sh"
fi

export PATH="$PATH:${HOME}/go/src/github.com/stackrox/workflow/bin"

# Use buildkit with docker
export DOCKER_BUILDKIT=1

# go variables
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# CodeReady containers
export PATH="$PATH:${HOME}/.crc/bin/oc"

# k3s cluster
export KUBECONFIG="${HOME}/.kube/k3s.yaml"
export KUBE_EDITOR="nvim"

# kubectl completion
if [ $commands[kubectl] ]; then
    source <(kubectl completion zsh)
fi

# Python binaries
export PATH="$PATH:${HOME}/Library/Python/3.9/bin/"

# My binaries before anything else
export PATH="${HOME}/.bin:$PATH"

# minikube completion
if [[ -f "${HOME}/.minikube-completion" ]]; then
    source "${HOME}/.minikube-completion"
fi

[ -f "${HOME}/.ghcup/env" ] && source "${HOME}/.ghcup/env" # ghcup-env

[ -f "${HOME}/.fzf.zsh" ] && source "${HOME}/.fzf.zsh"

# Java Home
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home"

PLUGINS_DIR="${ZSH}/plugins"
THEMES_DIR="${ZSH}/themes"

# Agnoster theme
source "${THEMES_DIR}/agnoster.zsh-theme"

# Plugins
for plugin in "${PLUGINS_DIR}"/*/*.zsh; do
    source "${plugin}"
done

# >>>> Vagrant command completion (start)
fpath=(/opt/vagrant/embedded/gems/gems/vagrant-2.3.7/contrib/zsh $fpath)
compinit
# <<<<  Vagrant command completion (end)
