#!/usr/bin/env zsh

# Enable zsh auto-completion
autoload -Uz compinit
compinit

# Enable bash completion compatibility
autoload bashcompinit
bashcompinit

# options
setopt share_history        # Share history between shells
setopt interactivecomments  # Comments on interactive shell
#   Changing directories
setopt auto_cd              # Execute cd if command doesn't exist but is a dir
setopt auto_pushd           # cd pushed old directory onto the directory stack
setopt pushd_ignore_dups
setopt pushdminus
#   Completion
setopt always_to_end
setopt auto_menu
setopt complete_in_word

# Highlight selection with tab completion
zstyle ':completion:*' menu select
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|=*' 'l:|=* r:|=*'

WORDCHARS=''

# emacs keybindings
bindkey -e

# History file configuration
[ -z "$HISTFILE" ] && HISTFILE="$HOME/.zsh_history"
[ "$HISTSIZE" -lt 50000 ] && HISTSIZE=50000
[ "$SAVEHIST" -lt 10000 ] && SAVEHIST=10000

# History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

# Path adjustments
#   Stackrox workflow scripts
export PATH="$PATH:${HOME}/go/src/github.com/stackrox/workflow/bin"
#   Go binaries
export PATH=$PATH:$GOPATH/bin
#   CodeReady containers
export PATH="$PATH:${HOME}/.crc/bin/oc"
#   My binaries before anything else
export PATH="${HOME}/.bin:$PATH"
#   ~/.local/bin
export PATH="$PATH:${HOME}/.local/bin"

if command -v yarn >/dev/null; then
    export PATH="$PATH:$(yarn global bin)"
fi

# alias
alias beggar="VAGRANT_CWD=${HOME}/vagrant/ vagrant"
alias k=kubectl
alias krox="kubectl -n stackrox"
alias dcu='docker context use'
alias ls='ls --color=auto'
alias egrep='grep -E'   # Silence egrep deprecation message
alias cdtemp='cd $(mktemp -d)'

# stackrox stuff
if [[ -f "${HOME}/.infra" ]]; then
    source "${HOME}/.infra"
fi

if [[ -f "${HOME}/go/src/github.com/stackrox/workflow/env.sh" ]]; then
    source "${HOME}/go/src/github.com/stackrox/workflow/env.sh"
fi

# kubectl completion
if [ $commands[kubectl] ]; then
    source <(kubectl completion zsh)
fi

# minikube completion
if [[ -f "${HOME}/.minikube-completion" ]]; then
    source "${HOME}/.minikube-completion"
fi

[ -f "${HOME}/.ghcup/env" ] && source "${HOME}/.ghcup/env" # ghcup-env

# FZF completion for multiple platforms
[ -f "${HOME}/.fzf.zsh" ] && source "${HOME}/.fzf.zsh"
[ -f /usr/share/fzf/shell/key-bindings.zsh ] && source /usr/share/fzf/shell/key-bindings.zsh

PLUGINS_DIR="${ZSH}/plugins"
THEMES_DIR="${ZSH}/themes"

eval "$(starship init zsh)"

# Plugins
for plugin in "${PLUGINS_DIR}"/*/*.zsh; do
    source "${plugin}"
done

# >>>> Vagrant command completion (start)
fpath=(/opt/vagrant/embedded/gems/gems/vagrant-2.3.7/contrib/zsh $fpath)
compinit
# <<<<  Vagrant command completion (end)

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

[[ ! -r /home/mmoltras/.opam/opam-init/init.zsh ]] || source /home/mmoltras/.opam/opam-init/init.zsh > /dev/null 2> /dev/null


# Load Angular CLI autocompletion.
source <(ng completion script)
