name: Update neovim dependencies
on:
  schedule:
    - cron: '0 0 * * 0'
  pull_request:

jobs:
  update-nvim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup nvim configuration directory
        run: |
          mkdir -p "${HOME}/.config"
          ln -s "${{ github.workspace }}/nvim" "${HOME}/.config/nvim"
          ls -la "${HOME}/.config"

      - name: Update neovim plugins
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install neovim
          nvim --headless "+Lazy! sync" +qa

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: '${{ secrets.GH_PAT }}'
          commit-message: Update NeoVim plugins
          branch: update-plugins
          signoff: false
          delete-branch: true
          title: Update NeoVim plugins
          body: |
            Weekly update of NeoVim plugins.
          draft: false
